version: '3.8'

services:
  # MySQL Database (batch-service와 carplatform 공유)
  mysql:
    image: mysql:8.0
    container_name: wondergoodlife-car-service
    environment:
      MYSQL_ROOT_PASSWORD: wondergoodlife_root123
      MYSQL_DATABASE: wondergoodlife_db
      MYSQL_USER: wondergoodlife_user
      MYSQL_PASSWORD: wondergoodlife_pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis (Message Broker for Celery)
  redis:
    image: redis:7-alpine
    container_name: batch_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application (Batch Service)
  api:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    container_name: batch_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
      - ../../uploads:/app/uploads
    environment:
      - DATABASE_URL=mysql+pymysql://wondergoodlife_user:wondergoodlife_pass123@mysql:3306/wondergoodlife_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:5173"]
      # Database Connection Pool Settings
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=30
      - DB_POOL_TIMEOUT=60
      - DB_POOL_RECYCLE=3600
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Worker (배치 작업 처리)
  celery_worker:
    build:
      context: ../../ 
      dockerfile: deployment/docker/Dockerfile
    container_name: batch_celery_worker
    command: celery -A celery_app worker --loglevel=info --concurrency=2
    volumes:
      - ../../:/app
      - ../../uploads:/app/uploads
    environment:
      - DATABASE_URL=mysql+pymysql://wondergoodlife_user:wondergoodlife_pass123@mysql:3306/wondergoodlife_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Database Connection Pool Settings
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=30
      - DB_POOL_TIMEOUT=60
      - DB_POOL_RECYCLE=3600
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Flower (Celery 모니터링)
  flower:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    container_name: batch_flower
    command: celery -A celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker

volumes:
  mysql_data:
  redis_data:

